FROM python:3.8-buster

RUN apt-get update 

RUN pip install -U pip

RUN mkdir /work

WORKDIR /work

RUN apt-get install -qy \
    texlive-full \
    python-pygments gnuplot \
    make git 
	
RUN apt-get install -qy emacs-nox

COPY requirements.txt /work

RUN pip install -r requirements.txt

COPY . /work

RUN pip install .

ENTRYPOINT ["/bin/bash"]

CMD ["doExport.sh", "-n", "10"]

